spring:
  datasource:
    url: jdbc:mariadb://14.36.168.82:3306/vincent_clinic?autoReconnect=true&useSSL=false&characterEncoding=utf-8&useUnicode=true&allowMultiQueries=true&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: vincent
    password: quddnjs@2023

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        show_sql: true
        format_sql: true
    defer-datasource-initialization: false

  thymeleaf:
    cache: false

server:
  port: 3300
