spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/joi-service;MODE=MariaDB;DATABASE_TO_LOWER=TRUE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        show_sql: true
        format_sql: true
    defer-datasource-initialization: false

  thymeleaf:
    cache: false

server:
  port: 3300
