spring:
  profiles:
    active: ${PROFILE}
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  servlet:
    session:
      timeout: 720m      # 60m * 12h
      cookie:
        max-age: 720m    # 60m * 12h
        name: SID
        http-only: true
        secure: true